### ISSUE TITLE
CW stutters

### ISSUE THREAD

**Issue by K6TD** [IronHeartConsulting/IBPV2#1]
Occasionally, the CW ID seems to stutter.  The dits don't get the right spacing after them.

**Comment by K6TD** [comment]
Peter commented it might be interrupts happening during the sending.  I masked interrupts off around the send routine.  This caused send_id to hang.  Investigating.

**Comment by wa5znu** [comment]
I have a fix for this ready that disables GPS read interrupts except during disciplining.

**Comment by wa5znu** [comment]
https://github.com/IronHeartConsulting/IBPV2/pull/7

**Comment by K6TD** [comment]
Haven't heard the stutter, BUT, GPS NEMA sentence receiving is bust at times.  See the serial console file.  It looks like the SoftwareSerial recv() started in either the middle of a byte, or the TinyGPS started in the middle of a sentence.

**Comment by K6TD** [comment]
Had put the serial console file in dropbox.  Send me a request to be added, if I didn't already.

**Comment by K6TD** [comment]
Closing.  Not heard since applying changes from Leigh's branch ISSUE-1.
