### ISSUE TITLE
sprintf and buff expensive in schedule.ino

### ISSUE THREAD

**Issue by wa5znu** [IronHeartConsulting/IBPV2#13]
This snippet in schedule.ino is expensive.  buff[128] might cause us to run out of RAM and cause odd effects elsewhere.  sprintf is a lot of code to bring in as well.

  char buff[128];
  sprintf(buff,"%03d",wall_ticks);
  FPPRINTRC(1,5,buff);

There are ways to get it done, but just overwriting with three spaces and letting it be left justified instead may be the safest and lowest-energy route.

**Comment by K6TD** [comment]
removed. and changed to left justified.  committed on branch bug-fixes.
