### ISSUE TITLE
LED (D13) doesn't come on during CW ID

### ISSUE THREAD

**Issue by K6TD** [IronHeartConsulting/IBPV2#3]
But, it does turn on during long Dash.

**Comment by GeoNomad** [comment]
I can't find the lower level code for the cwBeacon functionality to look at these issues. Am I missing something?

**Comment by K6TD** [comment]
Fixed.  SHA e8ab444f14f804c1e611ce34e53b1894f8e4d3e4.
Added code in send_id to turn on/off the LED.  Normally, this would be done in the rig.txon() function, but that function isn't called for CW ID.
