### ISSUE TITLE
Missing long dashes

### ISSUE THREAD

**Issue by K6TD** [IronHeartConsulting/IBPV2#9]
ND2T reports not hearing the 1st long dash - at least on 15m.

**Comment by K6TD** [comment]
This is problem of not putting the CW key "down" at the start of the dash.  Because of the way the time wheel works, problem is only true for 1st long Dash.

**Comment by K6TD** [comment]
still debugging.  It's definitely the last, or fourth dash that is missing.  This might be a race condition in schedule loop, as it looks like the next 1PPS happens before the scheduler exists.  Probably due to all the time taken up by all the debug print statements.

**Comment by wa5znu** [comment]
Good observation about the Heisenberg.  115Kbaud is pretty fast but maybe we should try taking the debug print out.

**Comment by K6TD** [comment]
surprizingly, fixing issue #13 caused the 3rd long dash, as well as the 4th long dash to not get sent.

**Comment by wa5znu** [comment]
taking out sprintf made something worse?

**Comment by K6TD** [comment]
Fixed with new schedule loop.  Committed into master
